/**
 * Placeholder types — regenerated by:
 *   supabase gen types typescript --linked > src/lib/database.types.ts
 * (done in Jalon 1, once the schema migrations are applied).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
